# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bill_code', models.CharField(max_length=10)),
                ('table_code', models.CharField(max_length=10)),
                ('table_floor', models.CharField(max_length=10)),
                ('staff_code', models.CharField(max_length=10)),
                ('bill_created', models.DateTimeField(default=datetime.datetime(2016, 1, 21, 2, 15, 27, 169773, tzinfo=utc))),
                ('bill_sale', models.BigIntegerField()),
                ('bill_service', models.BigIntegerField()),
                ('bill_total', models.BigIntegerField()),
                ('bill_cost', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bill_code', models.CharField(max_length=10)),
                ('food_code', models.CharField(max_length=10)),
                ('number', models.BigIntegerField()),
                ('cost_on_food', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('food_code', models.CharField(max_length=10)),
                ('type_code', models.CharField(max_length=10)),
                ('food_name', models.CharField(max_length=30)),
                ('food_cost', models.BigIntegerField()),
                ('food_unit', models.CharField(max_length=10)),
                ('foodde_scribe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('repeat_password', models.CharField(max_length=30)),
                ('host_mame', models.CharField(max_length=20)),
                ('host_porn', models.DateField()),
                ('host_address', models.CharField(max_length=30)),
                ('host_phone', models.CharField(max_length=12)),
                ('host_email', models.CharField(max_length=30)),
                ('host_create_date', models.DateTimeField(default=datetime.datetime(2016, 1, 21, 2, 15, 27, 170774, tzinfo=utc))),
                ('captcha_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('staff_code', models.CharField(max_length=10)),
                ('staff_password', models.CharField(max_length=20)),
                ('staff_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('table_code', models.CharField(max_length=10)),
                ('table_floor', models.CharField(max_length=10)),
                ('table_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('type_code', models.CharField(max_length=10)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
    ]
