# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160121_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=30)),
                ('service_location', models.CharField(max_length=30)),
                ('service_title', models.CharField(max_length=30)),
                ('service_discribe', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 16, 9, 26, 403957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='host_create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 16, 9, 26, 403957, tzinfo=utc), editable=False),
        ),
    ]
