# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160121_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 16, 26, 5, 284686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='host_create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 16, 26, 5, 285687, tzinfo=utc), editable=False),
        ),
    ]
